import { heldBackup, markBackedUp, mintBackup, revealSecretKey } from "@/accounts/backup";
import { activeDisplay } from "@/accounts/display";
import { storePasswordCredential } from "@/lib/credentialManager";

/**
 * Build the human-readable contents of the account backup `.txt`. The file is
 * self-explanatory: what it is, which account (npub), the encrypted key, how to
 * restore, and the password caveat. The raw nsec is intentionally NOT included —
 * the `ncryptsec` is the key already encrypted with the user's password, which is
 * the only safe way to put a key in a file.
 *
 * **The restore steps are a compatibility surface.** Every file ever downloaded
 * carries them and none can be edited afterwards, so the sign-in affordance has
 * to stay findable as `"Use your key"` however it is renamed internally — it is
 * printed below, and lives in `LoginPage` and `LoginFailureModal`.
 */
export function buildAccountBackupFileContent(ncryptsec: string, npub: string): string {
  return [
    "================================================",
    "  BRAINSTORM ACCOUNT BACKUP",
    "================================================",
    "",
    "This file is the only way to recover your Brainstorm account if you",
    "lose this device or clear your browser. Keep it somewhere safe.",
    "",
    "WHAT THIS IS",
    "Your account is a key pair on the Nostr network. The long code below is",
    "your private key, encrypted with the password you chose. It is safe to",
    "store because no one can use it without that password.",
    "",
    "YOUR ACCOUNT  (public - safe to share)",
    npub || "(unknown)",
    "",
    'YOUR ENCRYPTED RECOVERY KEY  (private - needs your password)',
    ncryptsec,
    "",
    "HOW TO RESTORE",
    '1. Open Brainstorm and choose Sign in -> "Use your key".',
    '2. Paste the encrypted recovery key line above (it starts with "ncryptsec").',
    "3. Enter your recovery password - the one you chose for this account.",
    "It also works in any Nostr app that supports encrypted keys",
    "(NIP-49, the standard encrypted-key format).",
    "",
    "IMPORTANT",
    "- Your password cannot be reset or recovered. If you forget it, this",
    "  backup cannot be opened.",
    "- Never store this file and your password in the same place.",
    "- Anyone who has this file AND your password controls your account.",
    "",
    "Generated by Brainstorm - nosfabrica.com",
    "",
  ].join("\n");
}

export type BackupCredential = { npub: string; ncryptsec: string };

/**
 * The (npub, ncryptsec) pair the backup is made of: what goes in the file, and
 * what the password manager stores (username=npub, password=ncryptsec).
 *
 * Async because minting waits for the Account to unlock; rejects when this
 * Account keeps its key elsewhere.
 */
export async function getEncryptedBackupCredential(password: string): Promise<BackupCredential> {
  return {
    npub: activeDisplay()?.npub ?? "",
    ncryptsec: await mintBackup(password),
  };
}

/**
 * Suggested download filename, personalized with the user's profile name so it's
 * recognizable later and distinguishes multiple accounts: e.g.
 * `brainstorm-account-backup-lira-flint.txt`. Slugified and length-capped; falls
 * back to the bare `${base}.txt` when there's no usable name.
 */
function backupFileName(base: string): string {
  const slug = (activeDisplay()?.displayName ?? "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-") // spaces/punctuation/emoji/non-ASCII → hyphen
    .replace(/^-+|-+$/g, "")
    .slice(0, 32)
    .replace(/-+$/, ""); // re-trim if the slice cut mid-hyphen
  return slug ? `${base}-${slug}.txt` : `${base}.txt`;
}

/** Trigger a local download of `content`. All client-side; nothing reaches a server. */
function downloadTextFile(content: string, name: string): void {
  const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = name;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

/**
 * The Backup this account already holds, as a credential. No minting: where the
 * password has just been checked *against* the stored ncryptsec, that ciphertext
 * is the artefact, and a re-mint would only cost another derivation.
 */
export function heldBackupCredential(): BackupCredential | null {
  const ncryptsec = heldBackup();
  return ncryptsec ? { npub: activeDisplay()?.npub ?? "", ncryptsec } : null;
}

/** Write a credential out as the backup `.txt`. */
export function downloadBackupFile(credential: BackupCredential): void {
  downloadTextFile(
    buildAccountBackupFileContent(credential.ncryptsec, credential.npub),
    backupFileName("brainstorm-account-backup"),
  );
}

/**
 * Hand the Backup the Account already holds over, every way there is: the file,
 * the password manager, and the Account marked as having been given it.
 *
 * The one hand-over every surface in the backup chain performs — the onboarding
 * step, the post-signup card and the recurring reminder — so none of them can
 * mark an Account backed up without also producing the file that claim is about.
 * Null where there is nothing to hand over.
 */
export function deliverBackup(): BackupCredential | null {
  const credential = heldBackupCredential();
  if (!credential) return null;
  downloadBackupFile(credential);
  // Best-effort and Chromium-only; the file is what matters, so never block on it.
  if (credential.npub && credential.ncryptsec) {
    void storePasswordCredential(credential.npub, credential.ncryptsec, credential.npub);
  }
  // "Backed up" means we offered and they accepted — browsers report nothing
  // about whether the file arrived.
  markBackedUp();
  return credential;
}

/**
 * Download the encrypted backup file, and hand back the credential it was built
 * from so a caller that also stores it in the password manager doesn't mint a
 * second one — minting costs a NIP-49 derivation, and two of them would differ.
 */
export async function downloadAccountBackup(password: string): Promise<BackupCredential> {
  const credential = await getEncryptedBackupCredential(password);
  downloadBackupFile(credential);
  return credential;
}

/**
 * Readable contents of a RAW (unencrypted) key backup. This is the recovery path
 * for users who'd rather not manage a password — but the file holds the raw nsec
 * in the clear, so the warning is deliberately blunt: the file alone is the whole
 * account.
 */
export function buildRawKeyBackupFileContent(nsec: string, npub: string): string {
  return [
    "================================================",
    "  BRAINSTORM ACCOUNT BACKUP  (UNENCRYPTED KEY)",
    "================================================",
    "",
    "This file recovers your Brainstorm account with NO password.",
    "",
    "⚠  READ THIS  ⚠",
    "The code below is your RAW private key. There is no password and no",
    "encryption. Anyone who gets this file controls your account completely —",
    "treat it like cash or a house key.",
    "  • Do NOT email it, screenshot it, or put it in cloud notes/chat.",
    "  • Store it somewhere only you can reach (a password manager, offline).",
    "  • If you want a safer backup, use the password-encrypted option instead.",
    "",
    "YOUR ACCOUNT  (public - safe to share)",
    npub || "(unknown)",
    "",
    "YOUR PRIVATE KEY  (SECRET - this IS your account)",
    nsec,
    "",
    "HOW TO RESTORE",
    '1. Open Brainstorm and choose Sign in -> "Use your key".',
    '2. Paste the private key line above (it starts with "nsec").',
    "It also works in any Nostr app.",
    "",
    "Generated by Brainstorm - nosfabrica.com",
    "",
  ].join("\n");
}

/**
 * Export the raw nsec to a downloadable `.txt` — a no-password recovery option so
 * a forgotten encryption password can't permanently lock a user out. Less safe
 * than the encrypted backup (the file is the key); the UI must warn accordingly.
 * Client-side only; rejects if the key can't be reached.
 */
export async function downloadRawKeyBackup(): Promise<void> {
  const nsec = await revealSecretKey();
  const npub = activeDisplay()?.npub ?? "";
  downloadTextFile(
    buildRawKeyBackupFileContent(nsec, npub),
    backupFileName("brainstorm-account-key"),
  );
}
