import { exportEncryptedKey, getCurrentUser } from "@/services/nostr";

/**
 * Build the human-readable contents of the account backup `.txt`. The file is
 * self-explanatory: what it is, which account (npub), the encrypted key, how to
 * restore, and the password caveat. The raw nsec is intentionally NOT included —
 * the `ncryptsec` is the key already encrypted with the user's password, which is
 * the only safe way to put a key in a file.
 */
export function buildAccountBackupFileContent(ncryptsec: string, npub: string): string {
  return [
    "================================================",
    "  BRAINSTORM ACCOUNT BACKUP",
    "================================================",
    "",
    "This file is the only way to recover your Brainstorm account if you",
    "lose this device or clear your browser. Keep it somewhere safe.",
    "",
    "WHAT THIS IS",
    "Your account is a key pair on the Nostr network. The long code below is",
    "your private key, encrypted with the password you chose. It is safe to",
    "store because no one can use it without that password.",
    "",
    "YOUR ACCOUNT  (public - safe to share)",
    npub || "(unknown)",
    "",
    'YOUR ENCRYPTED RECOVERY KEY  (private - needs your password)',
    ncryptsec,
    "",
    "HOW TO RESTORE",
    '1. Open Brainstorm and choose Sign in -> "Use your key".',
    '2. Paste the encrypted recovery key line above (it starts with "ncryptsec").',
    "3. Enter the password you set when you saved this backup.",
    "It also works in any Nostr app that supports encrypted keys",
    "(NIP-49, the standard encrypted-key format).",
    "",
    "IMPORTANT",
    "- Your password cannot be reset or recovered. If you forget it, this",
    "  backup cannot be opened.",
    "- Never store this file and your password in the same place.",
    "- Anyone who has this file AND your password controls your account.",
    "",
    "Generated by Brainstorm - nosfabrica.com",
    "",
  ].join("\n");
}

/**
 * Encrypt the stored key with `password`, build the readable backup file, and
 * trigger a local download. All client-side; nothing is sent to a server.
 * Throws if no key is available (callers wrap in try/catch).
 */
export function downloadAccountBackup(password: string): boolean {
  const ncryptsec = exportEncryptedKey(password);
  const npub = getCurrentUser()?.npub ?? "";
  const content = buildAccountBackupFileContent(ncryptsec, npub);

  const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = "brainstorm-account-backup.txt";
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
  return true;
}
