import { useState } from "react";
import { useLocation } from "wouter";
import { X, Check, ArrowRight, Users } from "lucide-react";
import { useActiveAccountDisplay } from "@/hooks/useActiveAccountDisplay";
import { useBackupNeed } from "@/hooks/useBackupNeed";
import { useSetupTasks } from "@/hooks/useSetupTasks";
import { useVerifiedNoFollows } from "@/hooks/useVerifiedNoFollows";
import { BACKUP_MESSAGE, BackupPrompt } from "@/components/BackupPrompt";
import { dismissPostSignup, usePostSignupDismissed } from "@/lib/postSignupDismissal";

/** Profile icon (from supplied profile.svg), recolored via currentColor. */
function ProfileIcon({ className }: { className?: string }) {
  return (
    <svg viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" className={className} aria-hidden="true">
      <path d="M12 14.18C9.81004 14.18 8.04004 12.4 8.04004 10.22C8.04004 8.03002 9.82004 6.26001 12 6.26001C14.18 6.26001 15.96 8.04002 15.96 10.22C15.96 12.4 14.19 14.18 12 14.18ZM12 7.75002C10.64 7.75002 9.54004 8.86002 9.54004 10.21C9.54004 11.57 10.65 12.67 12 12.67C13.35 12.67 14.46 11.56 14.46 10.21C14.46 8.86002 13.36 7.75002 12 7.75002Z" />
      <path d="M18.4202 22.23C18.0402 22.23 17.7102 21.94 17.6702 21.55C17.4202 18.86 14.9302 16.75 12.0002 16.75C9.06018 16.75 6.63017 18.78 6.34017 21.47C6.30017 21.88 5.92018 22.19 5.51018 22.13C5.10018 22.09 4.80017 21.71 4.85017 21.3C5.23017 17.85 8.30018 15.25 12.0002 15.25C15.7602 15.25 18.8402 17.9 19.1702 21.41C19.2102 21.82 18.9102 22.19 18.4902 22.23C18.4602 22.23 18.4402 22.23 18.4202 22.23Z" />
      <path d="M17 22.75H7C3.83 22.75 1.25 20.17 1.25 17V7C1.25 3.83 3.83 1.25 7 1.25H17C20.17 1.25 22.75 3.83 22.75 7V17C22.75 20.17 20.17 22.75 17 22.75ZM7 2.75C4.66 2.75 2.75 4.66 2.75 7V17C2.75 19.34 4.66 21.25 7 21.25H17C19.34 21.25 21.25 19.34 21.25 17V7C21.25 4.66 19.34 2.75 17 2.75H7Z" />
    </svg>
  );
}

/** Lock-in-circle icon (from supplied temp-lock.svg), recolored via currentColor. */
function BackupLockIcon({ className }: { className?: string }) {
  return (
    <svg viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" className={className} aria-hidden="true">
      <path d="M21.3604 7.96977H18.1504C17.7404 7.96977 17.4004 7.62977 17.4004 7.21977C17.4004 6.80977 17.7404 6.46977 18.1504 6.46977H20.6104V4.00977C20.6104 3.59977 20.9504 3.25977 21.3604 3.25977C21.7704 3.25977 22.1104 3.59977 22.1104 4.00977V7.21977C22.1104 7.62977 21.7704 7.96977 21.3604 7.96977Z" />
      <path d="M12 22.75C6.07 22.75 1.25 17.93 1.25 12C1.25 6.07 6.07 1.25 12 1.25C15.94 1.25 19.55 3.4 21.44 6.86C21.64 7.22 21.5 7.68 21.14 7.88C20.78 8.08 20.32 7.94 20.12 7.58C18.5 4.6 15.38 2.75 12 2.75C6.9 2.75 2.75 6.9 2.75 12C2.75 17.1 6.9 21.25 12 21.25C17.1 21.25 21.25 17.1 21.25 12C21.25 11.59 21.59 11.25 22 11.25C22.41 11.25 22.75 11.59 22.75 12C22.75 17.93 17.93 22.75 12 22.75Z" />
      <path d="M13.2999 17.1897H10.6899C10.1399 17.1897 9.62988 16.9397 9.29988 16.4997C8.96988 16.0597 8.86988 15.5097 9.01988 14.9797L9.68988 12.6197C9.00988 11.9897 8.62988 11.0997 8.62988 10.1697C8.62988 9.11973 9.10988 8.14973 9.93988 7.50973C10.7699 6.86973 11.8399 6.64973 12.8899 6.91973C14.0199 7.21973 14.9499 8.13973 15.2499 9.26973C15.5699 10.4997 15.2099 11.7697 14.3099 12.6197L14.9799 14.9797C15.1299 15.5097 15.0299 16.0597 14.6999 16.4997C14.3699 16.9397 13.8599 17.1897 13.3099 17.1897H13.2999ZM11.9899 8.29973C11.5799 8.29973 11.1899 8.42973 10.8599 8.68973C10.3999 9.04973 10.1299 9.57973 10.1299 10.1697C10.1299 10.7097 10.3599 11.2197 10.7699 11.5797C11.1499 11.9097 11.3099 12.4097 11.1799 12.8797L10.4599 15.3997C10.4299 15.4997 10.4699 15.5697 10.4999 15.6097C10.5299 15.6497 10.5899 15.6997 10.6899 15.6997H13.2999C13.3999 15.6997 13.4599 15.6397 13.4899 15.6097C13.5199 15.5697 13.5599 15.4997 13.5299 15.3997L12.8099 12.8797C12.6799 12.4097 12.8299 11.9097 13.2199 11.5797C13.7699 11.0997 13.9899 10.3797 13.7899 9.65973C13.6299 9.04973 13.1099 8.53973 12.5099 8.37973C12.3399 8.33973 12.1599 8.30973 11.9899 8.30973V8.29973Z" />
    </svg>
  );
}

/**
 * Calm, dismissible home-page onboarding nudge, driven by REAL account state:
 * - Brand-new in-app accounts (created here, key generated by us) get the full
 *   "Welcome / finish setting up" card — follow + add a photo + back up — until
 *   all three are done.
 * - Returning users (logged in with their own key) get a single focused
 *   "follow → switch on your scores" nudge, and only when they follow nobody.
 * Renders nothing once a user is set up, has dismissed it, or is anonymous.
 *
 * Its backup tile is the chain's second surface, between the wizard's last step
 * and the recurring reminder. It asks whatever the account is missing next —
 * the shared prompt decides which — rather than offering a backup of its own.
 */
export function PostSignupCard() {
  const [, navigate] = useLocation();
  const user = useActiveAccountDisplay();
  const pubkey = user?.pubkey ?? "";
  const setup = useSetupTasks();
  const backupNeed = useBackupNeed();

  const dismissed = usePostSignupDismissed(pubkey);
  const [backupMode, setBackupMode] = useState(false);
  /** The hand-over leaves the tile open: a phone loses downloads, so the offer stays. */
  const [delivered, setDelivered] = useState(false);

  const backedUp = setup.done.backup;
  const hasPhoto = setup.done.photo;
  const networkStarted = setup.done.network;

  // Full "Welcome / finish setting up" card → genuine first-timers only. Returning
  // users get a focused "follow → switch on scores" nudge, and ONLY when they
  // follow nobody (their profile + backup are already theirs).
  //
  // `delivered` keeps it up once the last task was the backup: handing the file
  // over completes the checklist, and unmounting on that click would take the
  // confirmation — and the offer to download it again — with it.
  const showFullCard = setup.eligible && (!setup.allDone || delivered);
  // `networkStarted` reads the local floor, which is 0 whenever the login-time
  // kind-3 fetch failed — don't nag a user who really follows people. Only the
  // relay-verified "none" shows the nudge; "checking" renders nothing (it's a
  // nudge, nothing is lost) and "has-follows" suppresses it for good.
  const followVerification = useVerifiedNoFollows(pubkey || undefined);
  const returningNeedsFollow = !setup.eligible && !networkStarted && followVerification === "none";

  // Signer accounts that follow people but haven't signed their kind-10040 used
  // to get an "Activate your scores" card here. The header's FinishSetupBanner
  // now carries that nudge (same relay-confident trigger, same cohort) into
  // /setup/activate, so a second card under the search bar was pure repetition.

  if (!user) return null;

  // Apple-style "material" tiles: soft translucent panel + hairline border +
  // subtle frost + whisper of shadow, so they read as refined inset surfaces
  // rather than stark white/dark blocks on the glass card.
  const tileBase =
    "group relative w-full text-left rounded-2xl bg-white/70 dark:bg-white/[0.07] backdrop-blur-sm border border-white/60 dark:border-white/[0.10] shadow-sm dark:shadow-none p-4 transition-all focus:outline-none focus-visible:ring-2 focus-visible:ring-brand-accent/40";
  const tileClickable = tileBase + " hover:bg-white/85 dark:hover:bg-white/[0.11] hover:border-brand-accent/40 hover:shadow-md active:scale-[0.995]";

  if (dismissed) return null;
  if (!showFullCard && !returningNeedsFollow) return null;

  const handleDismiss = () => dismissPostSignup(pubkey);

  // Returning user (own key) whose profile + backup are already theirs and just
  // hasn't built a Web of Trust yet → one focused nudge, no "Welcome / new
  // account / back up" framing.
  if (returningNeedsFollow) {
    return (
      <div
        className="relative w-full max-w-3xl mx-auto mt-6 sm:mt-8 overflow-hidden rounded-2xl border border-brand-accent/25 bg-gradient-to-br from-brand-deep/[0.04] to-brand-accent/[0.06] shadow-sm dark:shadow-none"
        data-testid="card-returning-follow-nudge"
      >
        <div className="relative p-5 sm:p-6">
          <button
            type="button"
            onClick={handleDismiss}
            className="absolute top-0 right-0 h-9 w-9 rounded-lg flex items-center justify-center text-slate-400 dark:text-slate-500 hover:text-slate-600 dark:hover:text-slate-300 hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors"
            aria-label="Dismiss"
            data-testid="button-returning-nudge-dismiss"
          >
            <X className="h-4 w-4" />
          </button>
          <div className="flex items-center gap-2.5 mb-2">
            <span className="text-[11px] font-mono font-bold tracking-[0.25em] text-brand-link dark:text-brand-link uppercase">Your network</span>
          </div>
          <h3 className="text-xl sm:text-2xl font-bold text-slate-900 dark:text-slate-100 tracking-tight" style={{ fontFamily: "var(--font-display)" }}>
            Switch on your scores
          </h3>
          <p className="mt-1.5 text-[15px] text-slate-700 dark:text-slate-200 leading-relaxed max-w-xl">
            Follow a few accounts and Brainstorm scores everyone through your own network.
          </p>
          <button
            type="button"
            onClick={() => navigate("/welcome")}
            className={`${tileClickable} mt-4 !border-brand-accent/50 !bg-brand-accent/[0.06]`}
            data-testid="tile-build-network"
          >
            <div className="flex items-center gap-3">
              <div className="h-10 w-10 rounded-xl bg-brand-primary flex items-center justify-center text-white shrink-0">
                <Users className="h-5 w-5" />
              </div>
              <div className="min-w-0">
                <div className="text-[15px] font-bold text-slate-900 dark:text-slate-100">Follow a few accounts</div>
                <div className="text-[13px] font-semibold text-brand-link dark:text-brand-link inline-flex items-center gap-1">
                  Turn on your scores
                  <ArrowRight className="h-3.5 w-3.5 group-hover:translate-x-0.5 transition-transform" />
                </div>
              </div>
            </div>
          </button>
        </div>
      </div>
    );
  }

  return (
    <>
      <div
        className="relative w-full max-w-3xl mx-auto mt-6 sm:mt-8 overflow-hidden rounded-2xl border border-brand-accent/25 bg-gradient-to-br from-brand-deep/[0.04] to-brand-accent/[0.06] shadow-sm dark:shadow-none"
        data-testid="card-post-signup"
      >
        <div className="relative z-10 p-5 sm:p-6">
          <button
            type="button"
            onClick={handleDismiss}
            className="absolute top-0 right-0 h-9 w-9 rounded-lg flex items-center justify-center text-slate-400 dark:text-slate-500 hover:text-slate-600 dark:hover:text-slate-300 hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors"
            aria-label="Dismiss"
            data-testid="button-post-signup-dismiss"
          >
            <X className="h-4 w-4" />
          </button>

          <div className="flex items-center gap-3 mb-3">
            <span className="shrink-0 text-[11px] font-mono font-bold tracking-[0.25em] text-brand-link dark:text-brand-link uppercase">
              Finish setting up
            </span>
            <div className="flex flex-1 items-center gap-1.5" aria-hidden="true">
              {[0, 1, 2].map((i) => (
                <div
                  key={i}
                  className={`h-1 flex-1 rounded-full transition-colors duration-500 ${
                    i < setup.doneCount ? "bg-brand-primary dark:bg-brand-link" : "bg-slate-200/70 dark:bg-white/[0.12]"
                  }`}
                />
              ))}
            </div>
            <span
              className="shrink-0 text-[11px] font-semibold text-slate-500 dark:text-slate-400 tabular-nums"
              data-testid="text-post-signup-progress"
            >
              {setup.doneCount} of 3
            </span>
          </div>
          <h3
            className="text-xl sm:text-2xl font-bold text-slate-900 dark:text-slate-100 tracking-tight"
            style={{ fontFamily: "var(--font-display)" }}
          >
            Welcome to <span className="text-brand-link">Brainstorm</span>
            {user.displayName ? `, ${user.displayName}` : ""}!
          </h3>
          <p className="mt-1.5 text-[15px] text-slate-700 dark:text-slate-200 leading-relaxed max-w-xl">
            {networkStarted
              ? "Back up your account and add a photo so people recognize you."
              : "Follow a few accounts to switch on your scores — then back up your account and add a photo so people recognize you."}
          </p>

          {/* Step 1 (payload-first): build your network — the activation step. */}
          {networkStarted ? (
            <div className={`${tileBase} mt-5`} data-testid="tile-network-done">
              <div className="flex items-center gap-3">
                <div className="h-10 w-10 rounded-xl bg-emerald-50 dark:bg-emerald-500/10 border border-emerald-200 dark:border-emerald-500/25 flex items-center justify-center text-emerald-600 dark:text-emerald-400 shrink-0">
                  <Check className="h-5 w-5" />
                </div>
                <div>
                  <div className="text-[15px] font-semibold text-slate-900 dark:text-slate-100">Network started</div>
                  <div className="text-[13px] text-emerald-700 dark:text-emerald-300">Your scores are calculating</div>
                </div>
              </div>
            </div>
          ) : (
            <button
              type="button"
              onClick={() => navigate("/welcome")}
              className={`${tileClickable} mt-5 !border-brand-accent/50 !bg-brand-accent/[0.06]`}
              data-testid="tile-build-network"
            >
              <div className="flex items-center gap-3">
                <div className="h-10 w-10 rounded-xl bg-brand-primary flex items-center justify-center text-white shrink-0">
                  <Users className="h-5 w-5" />
                </div>
                <div className="min-w-0">
                  <div className="text-[15px] font-bold text-slate-900 dark:text-slate-100">Build your network</div>
                  <div className="text-[13px] font-semibold text-brand-link dark:text-brand-link inline-flex items-center gap-1">
                    Follow accounts to turn on scores
                    <ArrowRight className="h-3.5 w-3.5 group-hover:translate-x-0.5 transition-transform" />
                  </div>
                </div>
              </div>
            </button>
          )}

          <div className="mt-3 grid sm:grid-cols-2 gap-3">
            {/* Complete your profile */}
            {hasPhoto ? (
              <div className={tileBase} data-testid="tile-complete-profile-done">
                <div className="flex items-center gap-3">
                  <div className="h-10 w-10 rounded-xl bg-emerald-50 dark:bg-emerald-500/10 border border-emerald-200 dark:border-emerald-500/25 flex items-center justify-center text-emerald-600 dark:text-emerald-400 shrink-0">
                    <Check className="h-5 w-5" />
                  </div>
                  <div>
                    <div className="text-[15px] font-semibold text-slate-900 dark:text-slate-100">Profile photo added</div>
                    <div className="text-[13px] text-emerald-700 dark:text-emerald-300">People can recognize you</div>
                  </div>
                </div>
              </div>
            ) : (
              <button
                type="button"
                onClick={() => navigate("/settings?tab=profile")}
                className={tileClickable}
                data-testid="tile-complete-profile"
              >
                <div className="flex items-center gap-3">
                  <div className="h-10 w-10 rounded-xl bg-white/70 dark:bg-white/[0.08] border border-white/70 dark:border-white/[0.12] flex items-center justify-center text-slate-600 dark:text-slate-300 shrink-0">
                    <ProfileIcon className="h-5 w-5" />
                  </div>
                  <div className="min-w-0">
                    <div className="text-[15px] font-semibold text-slate-900 dark:text-slate-100">Complete your profile</div>
                    <div className="text-[13px] font-semibold text-brand-link dark:text-brand-link inline-flex items-center gap-1">
                      Add a photo &amp; bio
                      <ArrowRight className="h-3.5 w-3.5 group-hover:translate-x-0.5 transition-transform" />
                    </div>
                  </div>
                </div>
              </button>
            )}

            {/* Back up your account — the chain's second surface. An open tile with
                nothing left to ask (another tab took the backup) closes rather than
                standing there with no button in it. */}
            {delivered || (backupMode && backupNeed) ? (
              <div className={tileBase} data-testid="tile-backup-form">
                <div className="flex items-center gap-2.5 mb-2.5">
                  <div className="h-10 w-10 rounded-xl bg-white/70 dark:bg-white/[0.08] border border-white/70 dark:border-white/[0.12] flex items-center justify-center text-slate-600 dark:text-slate-300 shrink-0">
                    <BackupLockIcon className="h-5 w-5" />
                  </div>
                  <span className="text-[15px] font-semibold text-slate-900 dark:text-slate-100">
                    {backupNeed ? BACKUP_MESSAGE[backupNeed].title : "Back up your account"}
                  </span>
                </div>
                {backupNeed && (
                  <p className="text-[12px] text-slate-500 dark:text-slate-400 mb-2">
                    {BACKUP_MESSAGE[backupNeed].body}
                  </p>
                )}
                <BackupPrompt need={backupNeed} onDelivered={() => setDelivered(true)} />
              </div>
            ) : backedUp ? (
              <div className={tileBase} data-testid="tile-backup-done">
                <div className="flex items-center gap-3">
                  <div className="h-10 w-10 rounded-xl bg-emerald-50 dark:bg-emerald-500/10 border border-emerald-200 dark:border-emerald-500/25 flex items-center justify-center text-emerald-600 dark:text-emerald-400 shrink-0">
                    <Check className="h-5 w-5" />
                  </div>
                  <div>
                    <div className="text-[15px] font-semibold text-slate-900 dark:text-slate-100">Backed up</div>
                    <div className="text-[13px] text-emerald-700 dark:text-emerald-300">Backup file downloaded</div>
                  </div>
                </div>
              </div>
            ) : (
              <button
                type="button"
                onClick={() => setBackupMode(true)}
                className={tileClickable}
                data-testid="tile-backup"
              >
                <div className="flex items-center gap-3">
                  <div className="h-10 w-10 rounded-xl bg-white/70 dark:bg-white/[0.08] border border-white/70 dark:border-white/[0.12] flex items-center justify-center text-slate-600 dark:text-slate-300 shrink-0">
                    <BackupLockIcon className="h-5 w-5" />
                  </div>
                  <div className="min-w-0">
                    <div className="text-[15px] font-semibold text-slate-900 dark:text-slate-100">Back up your account</div>
                    <div className="text-[13px] font-semibold text-brand-link dark:text-brand-link inline-flex items-center gap-1">
                      Save a backup file
                      <ArrowRight className="h-3.5 w-3.5 group-hover:translate-x-0.5 transition-transform" />
                    </div>
                  </div>
                </div>
              </button>
            )}
          </div>
        </div>
      </div>
    </>
  );
}
